# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"                                  # centos 7 as a base image
  config.vm.network "forwarded_port", guest: 80, host: 8082   # port forwarding (http://localhost:8082)
  
  config.vm.provider "virtualbox" do |vb|                     # VM properties
    vb.name = "nagios"
    vb.cpus = 2
    vb.memory = "1024"
  end

  config.vm.provision "ansible" do |ansible|                  # ansible playbook as a provisioner to begin 
    ansible.playbook = "./ansible/playbook.yml"               # Nagios installation right after VM creation
  end
end
