---
- hosts: wordpress                # host, defined in inventory.txt
  remote_user: ubuntu             # remote user to login with
  become: yes                     # become root
  roles:
    - roles/ansiblewordpress      # role, that installs and configures wordpress
    - roles/nrpe-install          # role, that installs and configures nrpe for monitoring