---
- name: Installing dependencies
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - apt-transport-https
    - software-properties-common

- name: Adding Grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Adding grafana repo to stable
  shell: echo "deb https://packages.grafana.com/oss/deb stable main" | tee -a /etc/apt/sources.list.d/grafana.list

- name: Update + Install Grafana
  apt: update_cache=true pkg=grafana state=latest

- name: Defining prometheus datasource
  template: src=data-source.j2 dest=/etc/grafana/provisioning/datasources/datasources.yaml

- name: Starting Grafana
  service: name=grafana-server state=started enabled=yes
