apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.configMap.name }}"
  namespace: "{{ .Values.namespace }}"
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
              "access":"proxy",
              "editable": true,
              "name": "prometheus",
              "orgId": 1,
              "type": "prometheus",
              "url": "http://prometheus-service.monitoring.svc:8080",
              "version": 1
            }
        ]
    }
