apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  namespace: "{{ .Values.namespace }}"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.grafana.port }}"
spec:
  selector:
    app: "{{ .Values.deployment.name }}"
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.grafana.port }}
      targetPort: {{ .Values.grafana.port }}
      nodePort: {{ .Values.service.nodePort }}
