---
- hosts: default
  become: yes                             # become root
  roles:
    - roles/docker-install                # role, that installs docker on the machine
    - roles/apache-container              # role, that creates and runs docker container with apache
    - roles/node-exporter-install         # role, that installs and configures node_exporter