deployment:
  name: "prometheus-deployment"
  replicas: 1
  app:
    name: "prometheus-server"
  container:
    name: "prometheus"
    image: "prom/prometheus"
    resources:
      requests:
        cpu: "500m"
        memory: "500M"
      limits:
        cpu: 1
        memory: "1Gi"
  volumes:
    configVolume:
      name: "prometheus-config-volume"
      path: "/etc/prometheus/"
    storageVolume:
      name: "prometheus-storage-volume"
      path: "/prometheus/"

service:
  name: "prometheus-service"
  ports:
    port: 8080
    nodePort: 30000

configMap:
  name: "prometheus-server-conf"

clusterRole:
  name: "prometheus"