---
- name: Creating node_exporter user
  user: name=node_exporter state=present

- name: Get node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter-1.7.0.linux-amd64.tar.gz

- name: Unpack node_exporter
  shell: cd /tmp && tar -xvf node_exporter-1.7.0.linux-amd64.tar.gz creates=/tmp/node_exporter-1.7.0.linux-amd64

- name: Moving node_exporter binary
  shell: cd /tmp/node_exporter-1.7.0.linux-amd64 && mv node_exporter /usr/local/bin creates=/usr/local/bin/node_exporter

- name: Creating node_exporter service file from template
  template: src=node-exp-service.j2 dest=/etc/systemd/system/node_exporter.service

- name: Starting node_exporter
  service: name=node_exporter state=started enabled=yes
